services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
      - db
    ports:
      - "4000:4000"
    command: sh -c "sleep 15 && npm run start:prod"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: chatty
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d chatty" ]
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
