import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../globals.css'
import InitAuthLayout from "@/providers/InitAuthLayout";
import QueryProvider from "@/providers/QueryClientProvider";
import SideMenu from "@/components/SideMenu";
import { Toaster } from 'react-hot-toast';
import { SocketProvider } from "@/providers/SocketProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Chatty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased ml-16`}>
        <InitAuthLayout>
          <QueryProvider>
            <SideMenu></SideMenu>
            <SocketProvider>
              {children}
              <Toaster position="bottom-right" />
            </SocketProvider>
          </QueryProvider>
        </InitAuthLayout>
      </body>
    </html >
  );
}
