import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import InitAuthLayout from "@/components/InitAuthLayout";
import QueryProvider from "@/components/QueryClientProvider";
import SideMenu from "@/components/SideMenu";
import { Toaster } from 'react-hot-toast';
import { SocketProvider } from "@/components/SocketProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ml-16`}
      >
        <InitAuthLayout>
          <QueryProvider>
            <SideMenu></SideMenu>
            <SocketProvider>
              {children}
              <Toaster position="bottom-right" />
            </SocketProvider>
          </QueryProvider>
        </InitAuthLayout>
      </body>
    </html >
  );
}
